### ISSUE TITLE
Test::More dependency in tests,  not in Meta

### ISSUE THREAD

**Issue by dangogh** [ingydotnet/yaml-pm#160]
On new CentOS 6.8 install (yes,  I know it's old..  Assuming other newer distros have same issue)

Many tests use Test::More,  but it doesn't get installed by cpan, so tests fail.   Should it be listed in Meta?

**Comment by karenetheridge** [comment]
Test::More is in core perl, which according to the licence agreement should be installed with the rest of the language by your distribution. Unfortunately CentOS (via Redhat) thinks that rule doesn't apply to it, so you need to install the 'perl-core' package separately to get all the bits you should have had all along.

(This is why it's a good idea to list *all* prereqs in META, even core modules. So that should be done here -- it looks like the `Meta` file is the one to update?)

**Comment by karenetheridge** [comment]
(see also http://www.nntp.perl.org/group/perl.perl5.porters/2009/08/msg149747.html)

**Comment by perlpunk** [comment]
I would also like to add that without the perl-core package you don't even have ExtUtils::MakeMaker, so perl Makefile.PL doesn't run (Tested only on CentOS 7).

But yeah, it should be listed as a prereq

**Comment by dangogh** [comment]
thanks -- good points.   I'll make sure perl-core is installed first,  but the prereq is still a good idea..

**Comment by perlpunk** [comment]
Fixed by #161 in YAML-1.18
