### ISSUE TITLE
$YAML::Numify=1 does not consider octal numbers 

### ISSUE THREAD

**Issue by XSven** [ingydotnet/yaml-pm#221]
YAML version 1.30

Why is an octal representation of a number not converted to its decimal value if $YAML::Numify is true?

```
perl -MYAML -MData::Dumper -E '$YAML::Numify=1; my $hashRef = Load("---\numask: 0022\n"); say Dumper($hashRef)'
VAR1 = {
          'umask' => '0022'
        };
```

I have expected to see the integer value 18 instead of the string '0022' in the dump output.

Which option should I use to change this behaviour?

**Comment by perlpunk** [comment]
YAML.pm was a very early implementation of YAML 1.0, and it did not recognize any special scalars except the tilde which results in 0.
I added the Numify option at some point, but it just turns scalars that look like numbers into numbers instead of strings.
If you want correct YAML 1.1 or 1.2 behaviour, you should try out YAML::PP.
https://metacpan.org/pod/YAML::PP

`0022` is an octal number in YAML 1.1, but not in 1.2, so you probably want this one:
https://metacpan.org/pod/YAML::PP::Schema::YAML1_1

For reference what is a number in 1.2/1.1 and what not have a look here: https://perlpunk.github.io/yaml-test-schema/schemas.html

**Comment by perlpunk** [comment]
Let me know if YAML::PP works for you.
I don't think anyone wants to do the work to add this to YAML.pm, in a backwards compatible way.

**Comment by XSven** [comment]
YAML::PP with yaml_version=> ["1.1"] works but this does not help. I am using a foreign CPAN module that uses YAML.pm. In the YAML.pm NOTE section I have read that YAML is an interface but it is not. At least it seems to have a kind of default implementation and I do not know how to inject other implementations like YAML::PP.

**Comment by perlpunk** [comment]
That comment in YAML.pm has been there for a long time.
I'm just the maintainer of it and can't say anything about Ingy's plans with it, but it isn't an interface for different YAML modules right now.
If you're stuck with YAML.pm, then in this case I can't help, I'm sorry.
But the CPAN module you are talking about should probably try to switch to YAML::PP, too.
Look at https://matrix.yaml.info/ to see how many tests YAML.pm is failing. And that doesn't even consider schema tests yet, e.g.the octal numbers we are talking about in your case.

I will try to at least make the note section a bit clearer and point to YAML::PP, if @ingydotnet agrees.

**Comment by XSven** [comment]
[Final fallback should be YAML::PP instead of YAML](https://rt.cpan.org/Ticket/Display.html?id=155324)
